baseURL = 'http://smsohan.com/'
languageCode = 'en-us'
title = "Sohan's Blog"
theme = 'ananke'
Paginate = 10

[markup.goldmark.renderer]
  unsafe = true
[permalinks]
  posts = '/blog/:year/:month/:day/:filename/'
  
[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Sohan's Blog"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 10
  body_classes = "body-text"
  post_content_classes = "body-text"

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/home/'
  weight = -110
